"""Update User model with new fields

Revision ID: b125c1634e62
Revises: 9b6c243c38fb
Create Date: 2024-09-16 16:22:14.255167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b125c1634e62'
down_revision = '9b6c243c38fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('user_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('profile_cv')
        batch_op.drop_column('name')
        batch_op.drop_column('profile_video')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_video', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('profile_cv', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('user_type')
        batch_op.drop_column('bio')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
