"""Create proposal table and update bio lenght for user

Revision ID: f099ec3accaf
Revises: bbf1d5d7e8c2
Create Date: 2024-09-18 10:35:59.406726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f099ec3accaf'
down_revision = 'bbf1d5d7e8c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=2040),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=sa.String(length=2040),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###
